name: rich_and_morty
description: Projeto Flutter para demonstrar o uso da API Rick and Morty.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  mobx: ^2.0.6
  flutter_mobx: ^2.0.6
  get_it: ^7.2.0
  google_sign_in: ^5.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.1.7
  mobx_codegen: ^2.0.6

flutter:
  uses-material-design: true
